### ISSUE TITLE
Re: Delete Account.

### ISSUE THREAD

**Issue by ovesemart** [SUNET/eduid-webapp#309]
When delete account, I need to log in one last time and then I will be redirected to the landing page with the “log in”-link marked in red. Clickin on that link will take mig right back to dashboard without any log in and without active account.
The account is in some limbo mode, since if I try to change password I will not be able to do the re-login proceedure.

<img width="1015" alt="Skärmavbild 2020-03-18 kl  08 58 26" src="https://user-images.githubusercontent.com/36661180/76964660-5d66a000-6923-11ea-86c6-73c2aa04048f.png">
<img width="936" alt="Skärmavbild 2020-03-18 kl  08 58 40" src="https://user-images.githubusercontent.com/36661180/76964668-60619080-6923-11ea-9d39-55bc6f97969a.png">

**Comment by johanlundberg** [comment]
Fixed by https://github.com/SUNET/eduid-common/pull/237 and https://github.com/SUNET/eduid-webapp/pull/311
