### ISSUE TITLE
Adding a newly removed email address -> error message when operation was successful

### ISSUE THREAD

**Issue by ovesemart** [SUNET/eduid-webapp#353]
When adding a newly removed email address return is an error message when operation was successful.
Steps to re-produce. 
1. add an email
2. remove the email
3. add the same email again

<img width="1123" alt="Skärmavbild 2020-06-10 kl  08 14 26" src="https://user-images.githubusercontent.com/36661180/84233501-bbee8500-aaf2-11ea-970f-75cbf9e73cce.png">

**Comment by johanlundberg** [comment]
Fixed by https://github.com/SUNET/eduid-webapp/pull/354
